# fly.toml app configuration file generated for examine on 2024-10-28T02:43:51-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'examine'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
