import { inter, lora } from '@/theme/default/fonts';
import '@/theme/default/globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Examine',
  description:
    'Generated by create next appExamine simplifies nutrition and supplementation — through meticulous analysis of the latest scientific research — to help answer your questions on how to be healthier.',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lora.variable} ${inter.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
